"use client";

import Drawer from "./components/drawer/drawer";
import Navbar from "./components/navbar/navbar";
import "./globals.css";
import Providers from "./providers";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <Navbar />
          <Drawer />

          {children}
        </Providers>
      </body>
    </html>
  );
}
